"""API applicative publique de File Janitor.

Cette couche orchestre scanner, planner, executor et historique sans dépendre
de Typer, Rich ou d'une future interface graphique.
"""

from file_janitor.application.remote import RemoteFolderInfo, is_remote_folder, remote_folder_info
from file_janitor.archiving import ArchiveFormat

from file_janitor.application.service import (
    HistoryDatabaseError,
    PlannedRecoveryState,
    AnalysisCapabilities,
    AnalysisItem,
    AnalysisResult,
    AnalysisSummary,
    CategoryDetails,
    CategorySummary,
    ClassificationGroupSummary,
    ClassificationMode,
    DuplicateGroup,
    DuplicateGroupMember,
    ResolvedDuplicateGroup,
    ExecuteResult,
    HistoryBatchSummary,
    HistoryOperationSummary,
    HistoryQueuedResumeValidation,
    RecoveryResolutionKind,
    SchedulePreview,
    UndoResult,
    analyze_archive_folder,
    analyze_empty_directories,
    analyze_folder,
    analyze_rename_folder,
    as_copy_actions,
    archive_actions,
    empty_directory_actions,
    build_analysis_result,
    build_report,
    classification_plan_config,
    classification_group_name,
    summarize_classification_groups,
    clean_actions,
    create_plan,
    duplicate_actions,
    duplicate_groups_for_selection,
    resolve_duplicate_groups_for_selection,
    resolve_selected_actions,
    execute_actions,
    execute_selected_actions,
    get_history_operation_summary,
    resume_queued_operations,
    validate_queued_resume_candidates,
    resolve_history_recovery_without_file_action,
    get_history_operations,
    get_history_summary,
    get_latest_undoable_batch_id,
    run_startup_crash_recovery,
    install_schedule,
    large_file_actions,
    list_history,
    list_schedules,
    mismatch_actions,
    preview_schedule,
    remove_schedule,
    rename_actions,
    render_report_html,
    scan_folder,
    sort_actions,
    summarize_analysis,
    undo_execution,
    write_report_html,
)

__all__ = [
    "ArchiveFormat",
    "HistoryDatabaseError",
    "AnalysisCapabilities",
    "AnalysisItem",
    "AnalysisResult",
    "AnalysisSummary",
    "CategoryDetails",
    "CategorySummary",
    "ClassificationGroupSummary",
    "ClassificationMode",
    "DuplicateGroup",
    "DuplicateGroupMember",
    "ResolvedDuplicateGroup",
    "ExecuteResult",
    "HistoryBatchSummary",
    "HistoryOperationSummary",
    "HistoryQueuedResumeValidation",
    "PlannedRecoveryState",
    "RecoveryResolutionKind",
    "SchedulePreview",
    "UndoResult",
    "analyze_archive_folder",
    "analyze_empty_directories",
    "analyze_folder",
    "analyze_rename_folder",
    "as_copy_actions",
    "archive_actions",
    "empty_directory_actions",
    "build_analysis_result",
    "build_report",
    "classification_plan_config",
    "classification_group_name",
    "summarize_classification_groups",
    "clean_actions",
    "create_plan",
    "duplicate_actions",
    "duplicate_groups_for_selection",
    "resolve_duplicate_groups_for_selection",
    "resolve_selected_actions",
    "execute_actions",
    "execute_selected_actions",
    "get_history_operation_summary",
    "resume_queued_operations",
    "validate_queued_resume_candidates",
    "resolve_history_recovery_without_file_action",
    "get_history_operations",
    "get_history_summary",
    "get_latest_undoable_batch_id",
    "run_startup_crash_recovery",
    "install_schedule",
    "is_remote_folder",
    "remote_folder_info",
    "RemoteFolderInfo",
    "large_file_actions",
    "list_history",
    "list_schedules",
    "mismatch_actions",
    "preview_schedule",
    "remove_schedule",
    "rename_actions",
    "render_report_html",
    "scan_folder",
    "sort_actions",
    "summarize_analysis",
    "undo_execution",
    "write_report_html",
]
# Types de configuration et parseurs exposés à travers la frontière
# applicative afin que les interfaces n'importent pas les sous-modules du
# moteur de planification directement.
from file_janitor.plan.builder import PlanConfig
from file_janitor.plan.grouping import DateGranularity, GroupBy
from file_janitor.plan.rules import RuleError, load_rules
from file_janitor.plan.templates import (
    DEFAULT_TEMPLATE_PATTERN,
    Template,
    TemplateError,
)
from file_janitor.report import DEFAULT_MAX_ITEMS_PER_CATEGORY
from file_janitor.scheduler import ScheduleError, ScheduledJob
from file_janitor.renaming import RenameTemplate, RenameTemplateError

__all__ += [
    "DEFAULT_MAX_ITEMS_PER_CATEGORY",
    "DEFAULT_TEMPLATE_PATTERN",
    "DateGranularity",
    "GroupBy",
    "PlanConfig",
    "RuleError",
    "ScheduleError",
    "ScheduledJob",
    "Template",
    "TemplateError",
    "RenameTemplate",
    "RenameTemplateError",
    "load_rules",
]
